version: "3.9"

services:
  db:
    container_name: db
    image: postgres:13.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "1234"
  web:
    image: university-timetable
    ports:
      - "8080:8080"
    depends_on:
      - db



