spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/university_hibernate
#    url: jdbc:postgresql://localhost:5432/univ_test
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  mvc:
    hiddenmethod:
      filter:
        enabled: true
logging:
  level:
    web: debug
    sql: debug
#    org.hibernate.SQL: debug
    ua.com.foxminded.university: debug