spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/university_hibernate
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  mvc:
    hiddenmethod:
      filter:
        enabled: true
logging:
  level:
    web: DEBUG
    sql: DEBUG
    ua.com.foxminded.university: DEBUG