spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/university_hibernate
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        highlight_sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  mvc:
    hiddenmethod:
      filter:
        enabled: true
#logging:
#  level:
#    web: debug
#    org.hibernate.SQL: debug
#    ua.com.foxminded.university: debug