spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/university_hibernate
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jackson:
    serialization:
      INDENT_OUTPUT: true
logging:
  level:
    ua.com.foxminded.university: DEBUG