spring:
  datasource:
#    jndi-name: java:comp/env/jdbc/university_hibernate
    url: jdbc:postgresql://localhost:5432/university_hibernate
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

#hibernate.dialect=org.hibernate.dialect.PostgreSQL10Dialect
#hibernate.format_sql=true
#hibernate.highlight_sql=true
#hibernate.use_sql_comments=true
#hibernate.hbm2ddl.auto=none
#hibernate.generate_statistics=true